name: Continuous Integration

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./src
          # Simply install from requirements
          pip install -r MLOps/requirements.txt

      - name: Test with pytest
        run: |
          python -m pytest -v

      - name: Run Integration Tests
        env:
          KAGGLE_USERNAME: "dummy"
          KAGGLE_KEY: "dummy"
        run: |
          # Create dummy directories and files in all possible expected locations
          mkdir -p models
          mkdir -p MLOps/models
          touch models/TrainedModel.pth
          touch MLOps/models/TrainedModel.pth
          
          # Ensure dummy data folders exist for the dataset test
          mkdir -p data/raw
          
          export PYTHONPATH=$PYTHONPATH:$(pwd)/MLOps/src
          pytest MLOps/tests/


